import { ConfigPlugin, withXcodeProject } from '@expo/config-plugins'
import * as fs from 'fs'
import * as path from 'path'

const withRNNetworkExports: ConfigPlugin = (config) => {
    return withXcodeProject(config, (config) => {
        const projectRoot = config.modRequest.platformProjectRoot
        const projectName = config.modRequest.projectName!

        const filePath = path.join(
            projectRoot,
            projectName,
            'RNNetworkExports.swift'
        )

        fs.writeFileSync(
            filePath,
            [
                '// Auto-generated by withRNNetworkExports',
                '// DO NOT EDIT — regenerated on every prebuild',
                '@_exported import RnNetwork',
            ].join('\n')
        )

        const project = config.modResults
        project.addSourceFile(
            `${projectName}/RNNetworkExports.swift`,
            { target: project.getFirstTarget().uuid },
            project.findPBXGroupKey({ name: projectName }) ?? undefined
        )

        return config
    })
}

export default withRNNetworkExports
