import { ConfigPlugin, withXcodeProject } from '@expo/config-plugins'
import * as fs from 'fs'
import * as path from 'path'

type Options = {
    targetName?: string
}

const withRNNetworkExports: ConfigPlugin<Options> = (config, options = {}) => {
    return withXcodeProject(config, (config) => {
        const projectRoot = config.modRequest.platformProjectRoot
        const targetName = options.targetName ?? getBrownfieldTargetName(config) ?? 'ScotiaBrownfield'

        const filePath = path.join(projectRoot, targetName, 'RNNetworkExports.swift')

        fs.mkdirSync(path.dirname(filePath), { recursive: true })
        fs.writeFileSync(
            filePath,
            [
                '// Auto-generated by withRNNetworkExports',
                '// DO NOT EDIT — regenerated on every prebuild',
                '@_exported @_implementationOnly import RnNetwork',
            ].join('\n')
        )

        const project = config.modResults
        const targetKey = project.findTargetKey(targetName)
        const groupKey = project.findPBXGroupKey({ name: targetName }) ?? undefined

        if (targetKey) {
            project.addSourceFile(
                `${targetName}/RNNetworkExports.swift`,
                { target: targetKey },
                groupKey
            )
        }

        return config
    })
}

function getBrownfieldTargetName(config: any): string | undefined {
    const plugins: any[] = config._internal?.pluginHistory
        ? Object.keys(config._internal.pluginHistory)
        : []
    // Try to read targetName from expo-brownfield plugin options in app.json
    const rawPlugins: any[] = config.plugins ?? []
    for (const plugin of rawPlugins) {
        if (Array.isArray(plugin) && plugin[0] === 'expo-brownfield') {
            return plugin[1]?.ios?.targetName
        }
    }
    return undefined
}

export default withRNNetworkExports
