import { ConfigPlugin, withFinalizedMod } from '@expo/config-plugins'
import * as fs from 'fs'
import * as path from 'path'

// xcode is a transitive dependency of @expo/config-plugins — always available in Expo projects
// eslint-disable-next-line @typescript-eslint/no-require-imports
const xcode = require('xcode')

type RNNetworkOptions = {
    brownfieldTarget?: string
    podModuleName?: string
}

// The bridge file re-exports the pod's types as typealiases so that the host app
// can reference them via `import ScotiaBrownfield` without creating a second,
// independent Swift type (which would have a separate static backing store for
// RNNetworkRegistry.provider).
const BRIDGE_FILE = 'RNNetworkBridge.swift'

// Legacy files that used to be copied — must be removed from the build phase on
// non-clean prebuilds to avoid "redefinition" compile errors.
const LEGACY_FILES = ['NetworkProvider.swift', 'RNNetworkRegistry.swift']

function bridgeFileContent(podModuleName: string): string {
    return [
        `// Auto-generated by @scotia/rn-network config plugin.`,
        `// Re-exports pod types so the host app can set RNNetworkRegistry.provider`,
        `// via \`import ScotiaBrownfield\` without creating a duplicate Swift type.`,
        `public import ${podModuleName}`,
        ``,
        `public typealias NetworkProvider = ${podModuleName}.NetworkProvider`,
        `public typealias RNNetworkRegistry = ${podModuleName}.RNNetworkRegistry`,
        ``,
    ].join('\n')
}

const withRNNetworkExports: ConfigPlugin<RNNetworkOptions> = (
    config,
    options = {}
) => {
    const brownfieldTargetName = options.brownfieldTarget ?? 'ScotiaBrownfield'
    const podModuleName = options.podModuleName ?? 'RnNetwork'

    // withFinalizedMod runs AFTER all withXcodeProject mods (including expo-brownfield's).
    // That guarantees the ScotiaBrownfield target already exists in the on-disk pbxproj
    // when our code runs, regardless of plugin order in app.json.
    return withFinalizedMod(config, ['ios', async (config) => {
        const platformProjectRoot = config.modRequest.platformProjectRoot

        // Locate the .xcodeproj folder
        const xcodeprojs = fs.readdirSync(platformProjectRoot)
            .filter((f: string) => f.endsWith('.xcodeproj'))
        if (!xcodeprojs.length) return config

        const pbxprojPath = path.join(
            platformProjectRoot,
            xcodeprojs[0],
            'project.pbxproj'
        )

        // Parse the pbxproj from disk — expo-brownfield has already created ScotiaBrownfield
        const project = xcode.project(pbxprojPath)
        project.parseSync()

        const targetUuid: string | null =
            project.findTargetKey(brownfieldTargetName) ??
            project.findTargetKey(`"${brownfieldTargetName}"`)

        if (!targetUuid) {
            const available = Object.entries(project.pbxNativeTargetSection())
                .filter(([k]: [string, unknown]) => !k.endsWith('_comment'))
                .map(([, t]: [string, any]) => t.name)
                .join(', ')
            throw new Error(
                `[withRNNetworkExports] Target "${brownfieldTargetName}" not found. ` +
                `Available targets: ${available}`
            )
        }

        // Locate the ScotiaBrownfield Sources build phase UUID by type, not by comment.
        // (expo-brownfield uses the target name as the comment, not the generic 'Sources' string.)
        const nativeTarget = project.pbxNativeTargetSection()[targetUuid]
        const pbxSources = project.hash.project.objects['PBXSourcesBuildPhase'] ?? {}
        const sourcesBuildPhaseUUID: string | undefined = (nativeTarget?.buildPhases ?? [])
            .find((phase: any) => pbxSources[phase.value] !== undefined)?.value

        if (!sourcesBuildPhaseUUID) {
            throw new Error(
                `[withRNNetworkExports] No Sources build phase found for target "${brownfieldTargetName}"`
            )
        }

        // ── 1. Remove legacy files from Sources phase (non-clean prebuild safety) ──────
        removeLegacyFiles(project, brownfieldTargetName, sourcesBuildPhaseUUID, LEGACY_FILES)

        // ── 2. Write the bridge file to disk ────────────────────────────────────────────
        const dest = path.join(platformProjectRoot, brownfieldTargetName, BRIDGE_FILE)
        fs.mkdirSync(path.dirname(dest), { recursive: true })
        fs.writeFileSync(dest, bridgeFileContent(podModuleName))

        // ── 3. Add bridge file to pbxproj ────────────────────────────────────────────────
        const filePath = `${brownfieldTargetName}/${BRIDGE_FILE}`

        let fileRefUUID: string | undefined = findExistingFileRef(project, filePath)
        if (!fileRefUUID) {
            const newUUID: string = project.generateUuid()
            fileRefUUID = newUUID
            project.hash.project.objects['PBXFileReference'][newUUID] = {
                isa: 'PBXFileReference',
                explicitFileType: 'undefined',
                fileEncoding: 4,
                includeInIndex: 0,
                lastKnownFileType: 'sourcecode.swift',
                name: BRIDGE_FILE,
                path: filePath,
                sourceTree: '"<group>"',
            }
            project.hash.project.objects['PBXFileReference'][`${newUUID}_comment`] = BRIDGE_FILE
        }

        // Skip if already in the ScotiaBrownfield Sources build phase
        const sourcesBuildPhase =
            project.hash.project.objects['PBXSourcesBuildPhase'][sourcesBuildPhaseUUID]
        const alreadyInPhase = (sourcesBuildPhase.files as any[]).some(
            (f: any) => f.comment === `${BRIDGE_FILE} in Sources`
        )

        if (!alreadyInPhase) {
            const buildFileUUID = project.generateUuid()
            const buildFileComment = `${BRIDGE_FILE} in Sources`

            project.hash.project.objects['PBXBuildFile'][buildFileUUID] = {
                isa: 'PBXBuildFile',
                fileRef: fileRefUUID,
                fileRef_comment: BRIDGE_FILE,
            }
            project.hash.project.objects['PBXBuildFile'][`${buildFileUUID}_comment`] =
                buildFileComment

            sourcesBuildPhase.files.push({
                value: buildFileUUID,
                comment: buildFileComment,
            })
        }

        // Write the modified pbxproj back to disk
        fs.writeFileSync(pbxprojPath, project.writeSync())

        return config
    }])
}

// Remove any legacy files from the ScotiaBrownfield Sources build phase and their
// associated PBXBuildFile / PBXFileReference entries. This is a no-op on clean
// prebuilds (where those entries never existed).
function removeLegacyFiles(
    project: any,
    brownfieldTargetName: string,
    sourcesBuildPhaseUUID: string,
    legacyFiles: string[]
): void {
    const pbxBuildFile = project.hash.project.objects['PBXBuildFile'] ?? {}
    const pbxFileRef = project.hash.project.objects['PBXFileReference'] ?? {}
    const sourcesBuildPhase =
        project.hash.project.objects['PBXSourcesBuildPhase'][sourcesBuildPhaseUUID]

    for (const file of legacyFiles) {
        const filePath = `${brownfieldTargetName}/${file}`
        const inSourcesComment = `${file} in Sources`

        // Find the PBXFileReference UUID for this legacy file
        const fileRefUUID = findExistingFileRef(project, filePath)

        // Remove from Sources build phase files array
        sourcesBuildPhase.files = (sourcesBuildPhase.files as any[]).filter(
            (f: any) => f.comment !== inSourcesComment
        )

        // Remove the corresponding PBXBuildFile entry (and its _comment sibling)
        for (const key of Object.keys(pbxBuildFile)) {
            if (key.endsWith('_comment')) continue
            const bf = pbxBuildFile[key]
            if (bf.fileRef === fileRefUUID || bf.fileRef === `"${fileRefUUID}"`) {
                delete pbxBuildFile[key]
                delete pbxBuildFile[`${key}_comment`]
            }
        }

        // Remove the PBXFileReference entry (and its _comment sibling)
        if (fileRefUUID) {
            delete pbxFileRef[fileRefUUID]
            delete pbxFileRef[`${fileRefUUID}_comment`]
        }
    }
}

function findExistingFileRef(project: any, filePath: string): string | undefined {
    const refs = project.hash.project.objects['PBXFileReference']
    for (const key of Object.keys(refs)) {
        if (key.endsWith('_comment')) continue
        const ref = refs[key]
        if (ref.path === filePath || ref.path === `"${filePath}"`) return key
    }
    return undefined
}

export default withRNNetworkExports
